@extends('layouts.app')

@section('title', 'GrowPec - Your Career Deserves A Better College | Admission Guidance')

@section('content')
<section class="relative isolate overflow-hidden bg-violet-950">
    @if($heroBanners->isNotEmpty())<img src="{{ $heroBanners->first()->image_url }}" alt="{{ $heroBanners->first()->title ?: 'GrowPEC admission guidance' }}" class="absolute inset-0 -z-20 size-full object-cover opacity-30">@endif
    <div class="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_10%_10%,rgba(168,85,247,.8),transparent_32%),linear-gradient(120deg,rgba(46,30,107,.96),rgba(15,10,42,.94))]"></div>
    <div class="mx-auto grid max-w-7xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-[1.2fr_.8fr] lg:px-8 lg:py-28"><div class="max-w-3xl"><span class="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-amber-200">India's admission counsellor</span><h1 class="mt-6 text-4xl font-extrabold tracking-tight text-white sm:text-5xl lg:text-6xl">Find the college that fits your future.</h1><p class="mt-6 max-w-2xl text-lg leading-8 text-violet-100">Compare verified institutions, programs and fees—and get clear, personal admission guidance.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('colleges.regular') }}" class="rounded-xl bg-amber-400 px-5 py-3 text-sm font-extrabold text-violet-950 hover:bg-amber-300">Explore colleges</a><button type="button" onclick="openEnquiryModal()" class="rounded-xl border border-white/30 bg-white/10 px-5 py-3 text-sm font-bold text-white hover:bg-white/20">Talk to an advisor</button></div></div><form action="{{ route('colleges.regular') }}" method="GET" class="h-fit rounded-3xl border border-white/15 bg-white/10 p-6 shadow-2xl backdrop-blur"><p class="text-sm font-bold text-amber-200">Find your best-fit college</p><label class="mt-5 block text-sm font-semibold text-white">Search colleges, courses or cities<input name="search" class="mt-2 w-full rounded-xl border-0 bg-white px-4 py-3 text-sm text-slate-900 outline-none ring-amber-300 focus:ring-2" placeholder="MBA, B.Tech, Delhi…"></label><button class="mt-4 w-full rounded-xl bg-white px-4 py-3 text-sm font-extrabold text-violet-950 hover:bg-violet-50">Search now</button></form></div>
</section>

@if(($siteSettings['features.enable_partner_strip'] ?? '1') == '1' && $partners->isNotEmpty())<section class="border-b border-slate-200 bg-white py-7"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p class="mb-5 text-center text-xs font-bold uppercase tracking-[.18em] text-slate-500">{{ $siteSettings['general.partner_strip_title'] ?? 'Trusted university partners' }}</p><div class="flex flex-wrap items-center justify-center gap-x-10 gap-y-5">@foreach($partners as $partner)<img src="{{ $partner->logo_url }}" alt="{{ $partner->name }}" class="h-10 max-w-36 object-contain grayscale transition hover:grayscale-0" loading="lazy">@endforeach</div></div></section>@endif

<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div class="mx-auto max-w-2xl text-center"><p class="text-sm font-bold uppercase tracking-[.18em] text-violet-700">Explore programs</p><h2 class="mt-3 text-3xl font-extrabold text-slate-950">Start with your dream degree</h2><p class="mt-3 text-slate-600">Choose a program and see colleges that offer it.</p></div><div class="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-4">@foreach($popularCourses as $course)<a href="{{ route('colleges.regular') }}?courses[]={{ $course->slug }}" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-violet-300 hover:shadow-lg"><span class="grid size-10 place-items-center rounded-xl bg-violet-100 text-lg text-violet-800">✦</span><h3 class="mt-4 font-bold text-slate-900 group-hover:text-violet-800">{{ $course->name }}</h3><p class="mt-1 text-xs text-slate-500">{{ $course->level }} · {{ $course->duration }}</p></a>@endforeach</div></section>

@foreach([['regular',$regularColleges,'Top regular colleges','Campus programs',route('colleges.regular')],['online',$onlineColleges,'Top online universities','Flexible learning',route('colleges.online')]] as [$kind,$colleges,$heading,$kicker,$url])<section class="{{ $kind === 'online' ? 'bg-violet-50' : 'bg-slate-50' }} py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-[.18em] text-violet-700">{{ $kicker }}</p><h2 class="mt-2 text-3xl font-extrabold text-slate-950">{{ $heading }}</h2></div><a href="{{ $url }}" class="rounded-xl border border-violet-900 px-4 py-2.5 text-sm font-bold text-violet-900 hover:bg-violet-900 hover:text-white">View all →</a></div><div class="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">@forelse($colleges as $college)<a href="{{ route('college.show',$college->slug) }}" class="group overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-xl"><div class="relative h-40"><img src="{{ $college->banner_url }}" alt="{{ $college->name }}" class="size-full object-cover" loading="lazy"><img src="{{ $college->logo_url }}" alt="" class="absolute -bottom-7 left-4 size-14 rounded-full border-4 border-white bg-white object-contain"></div><div class="p-5 pt-10"><h3 class="line-clamp-2 min-h-12 font-bold leading-6 text-slate-900 group-hover:text-violet-800">{{ $college->name }}</h3><p class="mt-3 text-sm text-slate-500">{{ $college->city }}, {{ $college->state }}</p><p class="mt-2 text-xs font-semibold text-slate-400">{{ $college->college_type ?: 'University / College' }}</p></div></a>@empty <p class="col-span-full py-8 text-center text-slate-500">Colleges are being updated. Check back soon.</p>@endforelse</div></div></section>@endforeach

@if(($siteSettings['ads.enable_home_ad'] ?? '1') == '1' && !empty($siteSettings['ads.home_banner']))<section class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><a href="{{ $siteSettings['ads.home_banner_link'] ?: 'tel:'.($siteSettings['general.support_phone'] ?? '8858285271') }}" class="block overflow-hidden rounded-3xl shadow-lg" @if(!str_starts_with($siteSettings['ads.home_banner_link'] ?? '', 'tel:')) target="_blank" @endif><img src="{{ asset($siteSettings['ads.home_banner']) }}" alt="Admission offer" class="h-40 w-full object-cover sm:h-56" loading="lazy"></a></section>@endif

<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div class="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p class="text-sm font-bold uppercase tracking-[.18em] text-violet-700">Why GrowPec</p><h2 class="mt-3 text-3xl font-extrabold text-slate-950">Clear choices. Confident decisions.</h2><p class="mt-5 leading-7 text-slate-600">We make college discovery simple, transparent, and personal—from your first search to your admission decision.</p><button type="button" onclick="openEnquiryModal()" class="mt-7 rounded-xl bg-violet-900 px-5 py-3 text-sm font-bold text-white hover:bg-violet-800">Get personal guidance</button></div><div class="grid gap-4 sm:grid-cols-3">@foreach([['Verified data','Accreditations, programs, fees and important college details in one place.'],['Fee guidance','Compare options and get support with scholarships and financing.'],['Expert support','Speak with a counsellor whenever you need help deciding.']] as [$title,$copy])<article class="rounded-2xl border border-slate-200 p-5"><span class="text-2xl text-amber-500">✓</span><h3 class="mt-4 font-bold">{{ $title }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $copy }}</p></article>@endforeach</div></div></section>

<section class="bg-violet-950 py-14"><div class="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 px-4 text-center sm:px-6 md:flex-row md:text-left lg:px-8"><div><h2 class="text-2xl font-extrabold text-white">Ready to find your best-fit college?</h2><p class="mt-2 text-violet-200">Speak with an admissions advisor today.</p></div><a href="tel:{{ $siteSettings['general.support_phone'] ?? '+918858285271' }}" class="rounded-xl bg-amber-400 px-5 py-3 text-sm font-extrabold text-violet-950 hover:bg-amber-300">Call {{ $siteSettings['general.support_phone'] ?? '+91 8858285271' }}</a></div></section>
@endsection
